### ISSUE TITLE
Add some basic tests

### ISSUE THREAD

**Issue by avivace** [gbdev/rgbenv#1]
We need some basic tests

1) 1. Install specific version
   1. Switch to it
   1. Compile example project

2) 1. Install specific version
   1. Install another specific version
   1. Check if both version are "available"

Also, we need to write a script that is able to run the scripts starting from a blank state (maybe in docker? or directly as github action).

**Comment by ZoomTen** [comment]
think I might want to run it directly in GH Actions if I were to write one

**Comment by avivace** [comment]
See how pyenv tests are made: https://github.com/pyenv/pyenv/tree/master/test.

They use bats: https://github.com/bats-core/bats-core

**Comment by avivace** [comment]
Done in https://github.com/gbdev/rgbenv/pull/5 !
