### ISSUE TITLE
Run tests in CI

### ISSUE THREAD

**Issue by avivace** [gbdev/rgbenv#3]

**Comment by ISSOtm** [comment]
In addition to a test suite, [ShellCheck](https://github.com/koalaman/shellcheck/#in-your-build-or-test-suites) should be a good addition. I use it locally, and it has served me well.

**Comment by avivace** [comment]
Done in https://github.com/gbdev/rgbenv/commit/9ac4d8a10daf896779a27a445aec597255da687d
Thanks @ISSOtm for the suggestion on Shellcheck!
